"""Exact-environment Claude CLI launcher and Max-plan attestation."""

from __future__ import annotations

import hashlib
import json
import logging
import os
import shlex
import subprocess
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping


logger = logging.getLogger(__name__)


class ClaudeAttestationError(RuntimeError):
    """Secret-free typed failure from the exact-environment auth probe."""

    permanent = False

    def __init__(self, message: str, *, diagnostic: Mapping[str, object]):
        super().__init__(message)
        self.diagnostic = dict(diagnostic)


class ClaudeAttestationTransientError(ClaudeAttestationError):
    """The auth probe did not produce an authoritative subscription state."""


class ClaudeAttestationRejectedError(ClaudeAttestationError):
    """The probe authoritatively reported a non-Max/non-first-party login."""

    permanent = True


@dataclass(frozen=True)
class ClaudeMaxAttestation:
    auth_method: str
    api_provider: str
    subscription_type: str
    checked_at: float
    account_key: str

    @property
    def included_usage(self) -> bool:
        return (
            self.auth_method == "claude.ai"
            and self.api_provider == "firstParty"
            and self.subscription_type == "max"
        )


_ATTESTATION_CACHE: dict[str, ClaudeMaxAttestation] = {}
_ATTESTATION_LOCK = threading.Lock()


def create_exact_env_cli_wrapper(
    real_cli: str | Path,
    exact_env: Mapping[str, str],
    wrapper_dir: str | Path,
    *,
    sandbox_profile: str | None = None,
) -> Path:
    """Create a 0700 launcher that execs the CLI through ``env -i``.

    ``ClaudeAgentOptions.env`` is only an overlay on the SDK parent's ambient
    environment. Pointing the SDK at this launcher via its public ``cli_path``
    option ensures the *actual* Claude CLI is a second process with an exact
    allowlisted environment, without mutating the Hermes process environment.
    """

    if os.name != "posix":
        raise RuntimeError("Exact Claude CLI environment is unsupported on this OS")
    real_path = Path(real_cli).expanduser().resolve()
    if not real_path.is_file():
        raise RuntimeError(f"Claude CLI does not exist: {real_path}")
    env_items = sorted((str(key), str(value)) for key, value in exact_env.items())
    digest = hashlib.sha256(
        json.dumps(
            [str(real_path), env_items, sandbox_profile], separators=(",", ":")
        ).encode()
    ).hexdigest()[:20]
    directory = Path(wrapper_dir).expanduser()
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    directory.chmod(0o700)
    wrapper = directory / f"claude-exact-env-{digest}"
    assignments = " ".join(
        f"{key}={shlex.quote(value)}" for key, value in env_items
    )
    command = shlex.quote(str(real_path))
    if sandbox_profile is not None:
        command = (
            "/usr/bin/sandbox-exec -p "
            f"{shlex.quote(sandbox_profile)} {command}"
        )
    content = (
        "#!/bin/sh\n"
        "# Generated by Hermes Agent; contains no provider credentials.\n"
        f"exec /usr/bin/env -i {assignments} {command} \"$@\"\n"
    )
    try:
        if wrapper.read_text(encoding="utf-8") == content:
            wrapper.chmod(0o700)
            return wrapper
    except OSError:
        pass
    temporary = directory / f".{wrapper.name}.{os.getpid()}.tmp"
    temporary.write_text(content, encoding="utf-8")
    temporary.chmod(0o700)
    os.replace(temporary, wrapper)
    wrapper.chmod(0o700)
    return wrapper


def invalidate_claude_auth_attestation(cli_wrapper: str | Path) -> None:
    with _ATTESTATION_LOCK:
        _ATTESTATION_CACHE.pop(str(Path(cli_wrapper).resolve()), None)


def attest_claude_max_auth(
    cli_wrapper: str | Path,
    *,
    cache_ttl_seconds: float = 60,
    max_attempts: int = 2,
    retry_delay_seconds: float = 0.15,
) -> ClaudeMaxAttestation:
    """Require same-binary, same-environment first-party Max authentication."""

    wrapper = Path(cli_wrapper).resolve()
    key = str(wrapper)
    now = time.time()
    with _ATTESTATION_LOCK:
        cached = _ATTESTATION_CACHE.get(key)
        if cached and now - cached.checked_at < cache_ttl_seconds:
            return cached
    required = {
        "loggedIn": True,
        "authMethod": "claude.ai",
        "apiProvider": "firstParty",
        "subscriptionType": "max",
    }
    attempts = max(int(max_attempts), 1)
    payload: dict[str, object] | None = None
    last_transient: ClaudeAttestationTransientError | None = None
    for attempt in range(1, attempts + 1):
        try:
            result = subprocess.run(
                [str(wrapper), "auth", "status"],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            last_transient = ClaudeAttestationTransientError(
                "Claude Max attestation probe timed out",
                diagnostic={"stage": "auth_status", "kind": "timeout", "attempt": attempt},
            )
        except OSError as exc:
            last_transient = ClaudeAttestationTransientError(
                "Claude Max attestation probe could not start",
                diagnostic={
                    "stage": "auth_status",
                    "kind": "spawn_error",
                    "errno": getattr(exc, "errno", None),
                    "attempt": attempt,
                },
            )
        else:
            stderr_hash = hashlib.sha256((result.stderr or "").encode()).hexdigest()[:16]
            stdout_hash = hashlib.sha256((result.stdout or "").encode()).hexdigest()[:16]
            if result.returncode != 0:
                last_transient = ClaudeAttestationTransientError(
                    "Claude Max attestation probe returned non-zero",
                    diagnostic={
                        "stage": "auth_status",
                        "kind": "nonzero_exit",
                        "returncode": int(result.returncode),
                        "stderr_sha256": stderr_hash,
                        "attempt": attempt,
                    },
                )
            else:
                try:
                    raw_payload = json.loads(result.stdout)
                except (TypeError, ValueError, json.JSONDecodeError):
                    last_transient = ClaudeAttestationTransientError(
                        "Claude Max attestation probe returned invalid JSON",
                        diagnostic={
                            "stage": "auth_status",
                            "kind": "invalid_json",
                            "stdout_sha256": stdout_hash,
                            "attempt": attempt,
                        },
                    )
                else:
                    if not isinstance(raw_payload, dict):
                        last_transient = ClaudeAttestationTransientError(
                            "Claude Max attestation probe returned a non-object payload",
                            diagnostic={
                                "stage": "auth_status",
                                "kind": "invalid_shape",
                                "attempt": attempt,
                            },
                        )
                    else:
                        missing = sorted(field for field in required if field not in raw_payload)
                        if missing:
                            last_transient = ClaudeAttestationTransientError(
                                "Claude Max attestation probe omitted required fields",
                                diagnostic={
                                    "stage": "auth_status",
                                    "kind": "missing_fields",
                                    "fields": missing,
                                    "attempt": attempt,
                                },
                            )
                        else:
                            mismatched = sorted(
                                field
                                for field, expected in required.items()
                                if raw_payload.get(field) != expected
                            )
                            if mismatched:
                                invalidate_claude_auth_attestation(wrapper)
                                raise ClaudeAttestationRejectedError(
                                    "Claude Max attestation rejected the exact-environment login",
                                    diagnostic={
                                        "stage": "auth_status",
                                        "kind": "subscription_mismatch",
                                        "fields": mismatched,
                                        "attempt": attempt,
                                    },
                                )
                            payload = raw_payload
                            break
        if attempt < attempts:
            time.sleep(max(float(retry_delay_seconds), 0.0))

    if payload is None:
        invalidate_claude_auth_attestation(wrapper)
        assert last_transient is not None
        logger.warning("Claude Max attestation transient failure: %s", last_transient.diagnostic)
        raise last_transient
    attestation = ClaudeMaxAttestation(
        auth_method="claude.ai",
        api_provider="firstParty",
        subscription_type="max",
        checked_at=now,
        account_key=hashlib.sha256(
            str(
                payload.get("accountUuid")
                or payload.get("email")
                or wrapper
            ).encode("utf-8")
        ).hexdigest()[:24],
    )
    with _ATTESTATION_LOCK:
        _ATTESTATION_CACHE[key] = attestation
    return attestation


__all__ = [
    "ClaudeAttestationError",
    "ClaudeAttestationRejectedError",
    "ClaudeAttestationTransientError",
    "ClaudeMaxAttestation",
    "attest_claude_max_auth",
    "create_exact_env_cli_wrapper",
    "invalidate_claude_auth_attestation",
]
