"""Exact-environment Claude CLI launcher and Max-plan attestation."""

from __future__ import annotations

import hashlib
import json
import logging
import os
import shlex
import subprocess
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping


logger = logging.getLogger(__name__)


class ClaudeAttestationError(RuntimeError):
    """Secret-free typed failure from the exact-environment auth probe."""

    permanent = False

    def __init__(self, message: str, *, diagnostic: Mapping[str, object]):
        super().__init__(message)
        self.diagnostic = dict(diagnostic)


class ClaudeAttestationTransientError(ClaudeAttestationError):
    """The auth probe did not produce an authoritative subscription state."""


class ClaudeAttestationRejectedError(ClaudeAttestationError):
    """The probe authoritatively reported a non-Max/non-first-party login."""

    permanent = True


@dataclass(frozen=True)
class ClaudeMaxAttestation:
    auth_method: str
    api_provider: str
    subscription_type: str
    checked_at: float
    account_key: str

    @property
    def included_usage(self) -> bool:
        return (
            self.auth_method == "claude.ai"
            and self.api_provider == "firstParty"
            and self.subscription_type == "max"
        )


_ATTESTATION_CACHE: dict[str, ClaudeMaxAttestation] = {}
_ATTESTATION_LOCK = threading.Lock()


def create_exact_env_cli_wrapper(
    real_cli: str | Path,
    exact_env: Mapping[str, str],
    wrapper_dir: str | Path,
    *,
    sandbox_profile: str | None = None,
) -> Path:
    """Create a 0700 launcher that execs the CLI through ``env -i``.

    ``ClaudeAgentOptions.env`` is only an overlay on the SDK parent's ambient
    environment. Pointing the SDK at this launcher via its public ``cli_path``
    option ensures the *actual* Claude CLI is a second process with an exact
    allowlisted environment, without mutating the Hermes process environment.
    """

    if os.name != "posix":
        raise RuntimeError("Exact Claude CLI environment is unsupported on this OS")
    real_path = Path(real_cli).expanduser().resolve()
    if not real_path.is_file():
        raise RuntimeError(f"Claude CLI does not exist: {real_path}")
    env_items = sorted((str(key), str(value)) for key, value in exact_env.items())
    digest = hashlib.sha256(
        json.dumps(
            [str(real_path), env_items, sandbox_profile], separators=(",", ":")
        ).encode()
    ).hexdigest()[:20]
    directory = Path(wrapper_dir).expanduser()
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    directory.chmod(0o700)
    wrapper = directory / f"claude-exact-env-{digest}"
    assignments = " ".join(
        f"{key}={shlex.quote(value)}" for key, value in env_items
    )
    command = shlex.quote(str(real_path))
    if sandbox_profile is not None:
        command = (
            "/usr/bin/sandbox-exec -p "
            f"{shlex.quote(sandbox_profile)} {command}"
        )
    content = (
        "#!/bin/sh\n"
        "# Generated by Hermes Agent; contains no provider credentials.\n"
        f"exec /usr/bin/env -i {assignments} {command} \"$@\"\n"
    )
    try:
        if wrapper.read_text(encoding="utf-8") == content:
            wrapper.chmod(0o700)
            return wrapper
    except OSError:
        pass
    temporary = directory / f".{wrapper.name}.{os.getpid()}.tmp"
    temporary.write_text(content, encoding="utf-8")
    temporary.chmod(0o700)
    os.replace(temporary, wrapper)
    wrapper.chmod(0o700)
    return wrapper


def invalidate_claude_auth_attestation(cli_wrapper: str | Path) -> None:
    with _ATTESTATION_LOCK:
        _ATTESTATION_CACHE.pop(str(Path(cli_wrapper).resolve()), None)


def _sanitize_observed(observed: "Mapping[str, object]") -> "dict[str, str]":
    """Render observed auth fields for diagnostics.

    ``loggedIn`` / ``authMethod`` / ``apiProvider`` / ``subscriptionType`` are
    short non-secret enums, but stringify + cap length so a malformed probe
    payload can never smuggle a large or structured value into a log line.
    """

    return {str(field): str(value)[:32] for field, value in observed.items()}


def attest_claude_max_auth(
    cli_wrapper: str | Path,
    *,
    cache_ttl_seconds: float = 60,
    max_attempts: int = 2,
    retry_delay_seconds: float = 0.15,
    mismatch_confirm_delay_seconds: float = 1.0,
) -> ClaudeMaxAttestation:
    """Require same-binary, same-environment first-party Max authentication.

    A value mismatch against the required first-party Max tuple is classified,
    not blindly treated as a permanent rejection. Claude Code transiently drops
    subscription metadata (notably ``subscriptionType`` -> null) while a token
    refresh fails its profile fetch, so a single non-authoritative snapshot must
    NOT fail-close a card. Only ``loggedIn:true`` WITH concrete (non-null) wrong
    values is authoritative, and even that is confirmed by a second re-probe
    before it becomes permanent; everything else is transient (retryable). This
    preserves exact-success-only billing — an attestation object is returned
    solely on the complete Max tuple — while ending the fail-closed whack-a-mole
    on architect cards (incident 2026-07-22).
    """

    wrapper = Path(cli_wrapper).resolve()
    key = str(wrapper)
    now = time.time()
    with _ATTESTATION_LOCK:
        cached = _ATTESTATION_CACHE.get(key)
        if cached and now - cached.checked_at < cache_ttl_seconds:
            return cached
    # Observed values of the first authoritative mismatch, held across attempts
    # so a permanent rejection is only raised once a re-probe confirms the same
    # concrete downgrade.
    pending_authoritative_mismatch: "dict[str, str] | None" = None
    required = {
        "loggedIn": True,
        "authMethod": "claude.ai",
        "apiProvider": "firstParty",
        "subscriptionType": "max",
    }
    attempts = max(int(max_attempts), 1)
    payload: dict[str, object] | None = None
    last_transient: ClaudeAttestationTransientError | None = None
    for attempt in range(1, attempts + 1):
        # Default inter-attempt spacing; widened only when we need a real gap to
        # let a transient token-refresh window clear before confirming a mismatch.
        next_delay = float(retry_delay_seconds)
        try:
            result = subprocess.run(
                [str(wrapper), "auth", "status"],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            last_transient = ClaudeAttestationTransientError(
                "Claude Max attestation probe timed out",
                diagnostic={"stage": "auth_status", "kind": "timeout", "attempt": attempt},
            )
        except OSError as exc:
            last_transient = ClaudeAttestationTransientError(
                "Claude Max attestation probe could not start",
                diagnostic={
                    "stage": "auth_status",
                    "kind": "spawn_error",
                    "errno": getattr(exc, "errno", None),
                    "attempt": attempt,
                },
            )
        else:
            stderr_hash = hashlib.sha256((result.stderr or "").encode()).hexdigest()[:16]
            stdout_hash = hashlib.sha256((result.stdout or "").encode()).hexdigest()[:16]
            if result.returncode != 0:
                last_transient = ClaudeAttestationTransientError(
                    "Claude Max attestation probe returned non-zero",
                    diagnostic={
                        "stage": "auth_status",
                        "kind": "nonzero_exit",
                        "returncode": int(result.returncode),
                        "stderr_sha256": stderr_hash,
                        "attempt": attempt,
                    },
                )
            else:
                try:
                    raw_payload = json.loads(result.stdout)
                except (TypeError, ValueError, json.JSONDecodeError):
                    last_transient = ClaudeAttestationTransientError(
                        "Claude Max attestation probe returned invalid JSON",
                        diagnostic={
                            "stage": "auth_status",
                            "kind": "invalid_json",
                            "stdout_sha256": stdout_hash,
                            "attempt": attempt,
                        },
                    )
                else:
                    if not isinstance(raw_payload, dict):
                        last_transient = ClaudeAttestationTransientError(
                            "Claude Max attestation probe returned a non-object payload",
                            diagnostic={
                                "stage": "auth_status",
                                "kind": "invalid_shape",
                                "attempt": attempt,
                            },
                        )
                    else:
                        missing = sorted(field for field in required if field not in raw_payload)
                        if missing:
                            last_transient = ClaudeAttestationTransientError(
                                "Claude Max attestation probe omitted required fields",
                                diagnostic={
                                    "stage": "auth_status",
                                    "kind": "missing_fields",
                                    "fields": missing,
                                    "attempt": attempt,
                                },
                            )
                        else:
                            mismatched = sorted(
                                field
                                for field, expected in required.items()
                                if raw_payload.get(field) != expected
                            )
                            # ``loggedIn`` must match by identity, not equality:
                            # a truthy non-bool (e.g. JSON ``1``) is ``== True``
                            # and would otherwise slip through as a valid login
                            # and be billed as included usage. Force it into the
                            # mismatch path (where it resolves non-authoritative
                            # → transient, never a silent success).
                            if (
                                raw_payload.get("loggedIn") is not True
                                and "loggedIn" not in mismatched
                            ):
                                mismatched = sorted([*mismatched, "loggedIn"])
                            if not mismatched:
                                payload = raw_payload
                                break
                            # A field disagreed with the required Max tuple.
                            # Only an authoritative reading — genuinely logged
                            # in AND every wrong field carrying a concrete
                            # (non-null) value — is a candidate for permanent
                            # rejection. A ``loggedIn`` that is not True, or a
                            # null subscription field, is a non-authoritative
                            # snapshot (typically a token-refresh blip) and is
                            # retried, not fail-closed.
                            observed = _sanitize_observed(
                                {field: raw_payload.get(field) for field in mismatched}
                            )
                            authoritative = raw_payload.get("loggedIn") is True and all(
                                raw_payload.get(field) is not None for field in mismatched
                            )
                            diag = {
                                "stage": "auth_status",
                                "kind": "subscription_mismatch",
                                "fields": mismatched,
                                "observed": observed,
                                "attempt": attempt,
                            }
                            if not authoritative:
                                last_transient = ClaudeAttestationTransientError(
                                    "Claude Max attestation returned a "
                                    "non-authoritative subscription state",
                                    diagnostic={**diag, "kind": "subscription_unsettled"},
                                )
                            elif pending_authoritative_mismatch == observed:
                                # A prior attempt already reported this exact
                                # concrete downgrade — it is stable, not a blip.
                                invalidate_claude_auth_attestation(wrapper)
                                raise ClaudeAttestationRejectedError(
                                    "Claude Max attestation rejected the exact-environment login",
                                    diagnostic=diag,
                                )
                            else:
                                # First authoritative mismatch: hold it and give
                                # the login a real gap to settle before the
                                # confirming re-probe decides permanence.
                                pending_authoritative_mismatch = observed
                                next_delay = max(
                                    next_delay, float(mismatch_confirm_delay_seconds)
                                )
                                last_transient = ClaudeAttestationTransientError(
                                    "Claude Max attestation awaiting mismatch confirmation",
                                    diagnostic={
                                        **diag,
                                        "kind": "subscription_mismatch_unconfirmed",
                                    },
                                )
        if attempt < attempts:
            time.sleep(max(next_delay, 0.0))

    if payload is None:
        invalidate_claude_auth_attestation(wrapper)
        assert last_transient is not None
        logger.warning("Claude Max attestation transient failure: %s", last_transient.diagnostic)
        raise last_transient
    attestation = ClaudeMaxAttestation(
        auth_method="claude.ai",
        api_provider="firstParty",
        subscription_type="max",
        checked_at=now,
        account_key=hashlib.sha256(
            str(
                payload.get("accountUuid")
                or payload.get("email")
                or wrapper
            ).encode("utf-8")
        ).hexdigest()[:24],
    )
    with _ATTESTATION_LOCK:
        _ATTESTATION_CACHE[key] = attestation
    return attestation


__all__ = [
    "ClaudeAttestationError",
    "ClaudeAttestationRejectedError",
    "ClaudeAttestationTransientError",
    "ClaudeMaxAttestation",
    "attest_claude_max_auth",
    "create_exact_env_cli_wrapper",
    "invalidate_claude_auth_attestation",
]
