"""Host-account HOME passthrough for selected local CLIs.

Hermes normally runs subprocesses with ``HOME={HERMES_HOME}/home`` so profile
state (git, ssh, gh, npm, etc.) stays isolated.  A few host-installed CLIs use
OAuth/auth state that deliberately belongs to the OS account.  For those CLIs,
we install a tiny PATH shim that keeps the parent process profile-isolated but
execs the real command with ``HOME`` restored to the host account home.

The current allowlist is intentionally narrow: Claude Code (``claude``).
"""

from __future__ import annotations

import os
import shlex
import shutil
import stat
from pathlib import Path

from hermes_constants import get_hermes_home, get_host_user_home

_HOST_HOME_CLI_NAMES: tuple[str, ...] = ("claude",)
_SHIM_DIR_ENV = "HERMES_HOST_CLI_SHIM_DIR"
_HOST_HOME_ENV = "HERMES_HOST_HOME"


def _path_parts(path_value: str) -> list[str]:
    return [part for part in (path_value or "").split(os.pathsep) if part]


def _without_shim_dir(path_value: str, shim_dir: Path) -> str:
    shim_resolved = str(shim_dir.resolve())
    kept: list[str] = []
    for part in _path_parts(path_value):
        try:
            if str(Path(part).resolve()) == shim_resolved:
                continue
        except OSError:
            if part == str(shim_dir):
                continue
        kept.append(part)
    return os.pathsep.join(kept)


def _find_real_command(command: str, env: dict[str, str], shim_dir: Path) -> str | None:
    """Find *command* on PATH while ignoring our own shim directory."""
    search_path = _without_shim_dir(env.get("PATH", os.environ.get("PATH", "")), shim_dir)
    found = shutil.which(command, path=search_path)
    if not found:
        return None
    try:
        found_path = Path(found).resolve()
        if found_path.parent == shim_dir.resolve():
            return None
        return str(found_path)
    except OSError:
        return found


def _write_posix_home_shim(shim_path: Path, real_binary: str) -> None:
    quoted_real = shlex.quote(real_binary)
    content = f"""#!/bin/sh
# Generated by Hermes Agent. Do not store credentials here.
if [ -n "${{HERMES_CLAUDE_HOME:-}}" ]; then
  export HOME="$HERMES_CLAUDE_HOME"
elif [ -n "${{HERMES_HOST_HOME:-}}" ]; then
  export HOME="$HERMES_HOST_HOME"
fi
exec {quoted_real} "$@"
"""
    existing = None
    try:
        existing = shim_path.read_text(encoding="utf-8")
    except OSError:
        pass
    if existing != content:
        shim_path.write_text(content, encoding="utf-8")
    mode = shim_path.stat().st_mode
    shim_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def prepare_host_home_cli_shims(env: dict[str, str]) -> dict[str, str]:
    """Install local PATH shims for host-auth CLIs and update *env* in-place.

    The parent process and normal shell commands keep their profile-local HOME.
    Only the allowlisted CLI process receives ``HOME=$HERMES_HOST_HOME`` through
    the generated wrapper.  If the host home or real binary cannot be resolved,
    this is a safe no-op apart from setting ``HERMES_HOST_HOME`` when known.
    """
    host_home = get_host_user_home()
    if not host_home:
        return env
    env[_HOST_HOME_ENV] = host_home

    # Native Windows needs a .cmd/PowerShell shim; avoid partial behavior there.
    if os.name == "nt":
        return env

    try:
        shim_dir = get_hermes_home() / "cache" / "host-cli-shims"
        shim_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
        try:
            shim_dir.chmod(0o700)
        except OSError:
            pass
    except OSError:
        return env

    wrote_any = False
    for command in _HOST_HOME_CLI_NAMES:
        real = _find_real_command(command, env, shim_dir)
        if not real:
            continue
        try:
            _write_posix_home_shim(shim_dir / command, real)
            wrote_any = True
        except OSError:
            continue

    if wrote_any:
        env[_SHIM_DIR_ENV] = str(shim_dir)
        path_parts = _path_parts(env.get("PATH", os.environ.get("PATH", "")))
        shim_str = str(shim_dir)
        if shim_str not in path_parts:
            env["PATH"] = os.pathsep.join([shim_str, *path_parts]) if path_parts else shim_str
    return env


def shell_reprepend_host_cli_shim_path() -> str:
    """Return a POSIX shell snippet that re-prepends the host CLI shim dir.

    Login shells and Hermes session snapshots can reset PATH after the Python
    environment is prepared.  Put this snippet after shell init/snapshot restore
    and before the user command so the shim remains first when configured.
    """
    return (
        'if [ -n "${HERMES_HOST_CLI_SHIM_DIR:-}" ]; then\n'
        '  case ":$PATH:" in\n'
        '    *":$HERMES_HOST_CLI_SHIM_DIR:"*) ;;\n'
        '    *) export PATH="$HERMES_HOST_CLI_SHIM_DIR:$PATH" ;;\n'
        '  esac\n'
        'fi'
    )


__all__ = [
    "prepare_host_home_cli_shims",
    "shell_reprepend_host_cli_shim_path",
]
